name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Instalar dependências
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install -r requirements.txt
        pip install pytest ruff

    - name: Rodar Linter (ruff)
      run: |
        source .venv/bin/activate
        ruff check .

    - name: Rodar Testes (pytest)
      run: |
        source .venv/bin/activate
        pytest
